/****************************************************************************
*
*                          PUBLIC DOMAIN NOTICE                         
*         Lister Hill National Center for Biomedical Communications
*                      National Library of Medicine
*                      National Institues of Health
*           United States Department of Health and Human Services
*                                                                         
*  This software is a United States Government Work under the terms of the
*  United States Copyright Act. It was written as part of the authors'
*  official duties as United States Government employees and contractors
*  and thus cannot be copyrighted. This software is freely available
*  to the public for use. The National Library of Medicine and the
*  United States Government have not placed any restriction on its
*  use or reproduction.
*                                                                        
*  Although all reasonable efforts have been taken to ensure the accuracy 
*  and reliability of the software and data, the National Library of Medicine
*  and the United States Government do not and cannot warrant the performance
*  or results that may be obtained by using this software or data.
*  The National Library of Medicine and the U.S. Government disclaim all
*  warranties, expressed or implied, including warranties of performance,
*  merchantability or fitness for any particular purpose.
*
***************************************************************************/

% File:     semantic_groups.pl
% Module:   semantic_groups
% Author:   MF, NLS
% Date:     4/3/2003
% Purpose:  A file with updated semgroups.
% To be used by any program that twants to check if two lists with semantic types
% share a semantic type that belong to the same semantic groups defined in this file.
% This module itself is completely generated by a perl program called Semgroup_to_prolog.perl
% given the appropriate Semantic Group file (defined in Semgroup_to_prolog.perl).
% It returns the Semantic Group that matched in Groupname. It is now being used by SemSpec.
% It is not very effcient because I am passing unbound variables and attempting to match
% the exact semantic type in a specific order from more specific to more general
% This required some reordering of the semantic groups after they were automatically generated.
% Is this really necessary ?
% If I do not do that I might end up with a predication that a more general
% semantic type ISA a more specific semantic type.

% ----- Module declaration and exported predicates

:- module(semantic_groups, [
	semantic_group/3,
	semgen_semantic_group/2,
	semrep_semantic_group/2
   ]).

semantic_group(Domain, GroupName, Members) :-
	( Domain == genetics ->
	  semgen_semantic_group(GroupName, Members)
	; semrep_semantic_group(GroupName, Members)
	).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%% SEMGEN SEMANTIC GROUPS %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% ----- Anatomy
/* From UMLS
ANAT|Anatomy|T017|Anatomical Structure|anst
ANAT|Anatomy|T029|Body Location or Region|blor
ANAT|Anatomy|T023|Body Part, Organ, or Organ Component|bpoc
ANAT|Anatomy|T030|Body Space or Junction|bsoj
ANAT|Anatomy|T031|Body Substance|bdsu
ANAT|Anatomy|T022|Body System|bdsy
ANAT|Anatomy|T025|Cell|cell
ANAT|Anatomy|T026|Cell Component|celc
ANAT|Anatomy|T018|Embryonic Structure|emst
ANAT|Anatomy|T021|Fully Formed Anatomical Structure|ffas
ANAT|Anatomy|T024|Tissue|tisu
*/

semgen_semantic_group(anat,
		      [ anst, blor, bpoc, bsoj, bdsu, cell, celc, emst, ffas, tisu ]).


% ----- Disorders
/* From UMLS
DISO|Disorders|T020|Acquired Abnormality|acab
DISO|Disorders|T190|Anatomical Abnormality|anab
DISO|Disorders|T049|Cell or Molecular Dysfunction
DISO|Disorders|T019|Congenital Abnormality|cgab
DISO|Disorders|T047|Disease or Syndrome|dsyn
DISO|Disorders|T050|Experimental Model of Disease
DISO|Disorders|T033|Finding|fndg
DISO|Disorders|T037|Injury or Poisoning|inpo
DISO|Disorders|T048|Mental or Behavioral Dysfunction|mobd
DISO|Disorders|T191|Neoplastic Process|neop
DISO|Disorders|T046|Pathologic Function|patf
DISO|Disorders|T184|Sign or Symptom|sosy

*/

semgen_semantic_group(diso,
		      [ acab, anab, cgab, dsyn, inpo, mobd, neop, patf ]).

% ----- Genetic group

/* From UMLS
GENE|Genes & Molecular Sequences|T087|Amino Acid Sequence|amas
GENE|Genes & Molecular Sequences|T088|Carbohydrate Sequence|crbs
GENE|Genes & Molecular Sequences|T028|Gene or Genome|gngm
GENE|Genes & Molecular Sequences|T085|Molecular Sequence|mosq
GENE|Genes & Molecular Sequences|T086|Nucleotide Sequence|nusq

'Amino acid, peptide, or protein' added to genetics_group

*/

semgen_semantic_group(gene,
		      [ aapp, gngm, nnon, nusq ]).

/* From UMLS
CHEM|Chemicals & Drugs|T116|Amino Acid, Peptide, or Protein
CHEM|Chemicals & Drugs|T195|Antibiotic
CHEM|Chemicals & Drugs|T123|Biologically Active Substance
CHEM|Chemicals & Drugs|T122|Biomedical or Dental Material
CHEM|Chemicals & Drugs|T118|Carbohydrate
CHEM|Chemicals & Drugs|T103|Chemical
CHEM|Chemicals & Drugs|T120|Chemical Viewed Functionally
CHEM|Chemicals & Drugs|T104|Chemical Viewed Structurally
CHEM|Chemicals & Drugs|T200|Clinical Drug
CHEM|Chemicals & Drugs|T111|Eicosanoid
CHEM|Chemicals & Drugs|T196|Element, Ion, or Isotope
CHEM|Chemicals & Drugs|T126|Enzyme
CHEM|Chemicals & Drugs|T131|Hazardous or Poisonous Substance
CHEM|Chemicals & Drugs|T125|Hormone
CHEM|Chemicals & Drugs|T129|Immunologic Factor
CHEM|Chemicals & Drugs|T130|Indicator, Reagent, or Diagnostic Aid
CHEM|Chemicals & Drugs|T197|Inorganic Chemical
CHEM|Chemicals & Drugs|T119|Lipid
CHEM|Chemicals & Drugs|T124|Neuroreactive Substance or Biogenic Amine
CHEM|Chemicals & Drugs|T114|Nucleic Acid, Nucleoside, or Nucleotide
CHEM|Chemicals & Drugs|T109|Organic Chemical
CHEM|Chemicals & Drugs|T115|Organophosphorus Compound
CHEM|Chemicals & Drugs|T121|Pharmacologic Substance
CHEM|Chemicals & Drugs|T192|Receptor
CHEM|Chemicals & Drugs|T110|Steroid
CHEM|Chemicals & Drugs|T127|Vitamin

Removed "Amino Acid, Peptide, or Protein" and "Nucleic Acid, Nucleoside, or Nucleotide".

*/

semgen_semantic_group(chem,
		      [ antb, bacs, bodm, carb, chem, chvf, chvs, clnd, eico, elii, enzy, hops,
			horm, imft, irda, inch, lipd, nsba, orch, opco, phsu, rcpt, strd, vita ]).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%% SEMREP SEMANTIC GROUPS %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

semrep_semantic_group(tmod, [aapp, antb, bacs, carb, chem, chvf, chvs, clnd, % old chem semgroup
			     eico, elii, enzy, hops, horm, imft, inch, lipd, % old chem semgroup
			     nnon, nsba, opco, orch, phsu, rcpt, strd, vita, % old chem semgroup
			     medd, topp]).

semrep_semantic_group(acti, [acty, bhvr, dora, evnt, gora, inbe, mcha, ocac, socb]).

%The rules for hypernyms Taxonomic relations do not apply for Meronomies (part_of)
semrep_semantic_group(anat, [anst, bdsu, bdsy, blor, bpoc, bsoj, celc, cell, emst, ffas, tisu]).

semrep_semantic_group(conc, [clas, cnce, ftcn, grpa, idcn, inpr, lang, qlco, qnco, rnlw, spco, tmco]).

semrep_semantic_group(devi, [drdd, resd]). % moved medd to tmod

semrep_semantic_group(diso, [acab, anab, cgab, comd, dsyn, fndg, inpo, mobd, neop, patf, sosy]).

semrep_semantic_group(gene, [aapp, amas, crbs, gngm, mosq, nusq]).

semrep_semantic_group(geog, [geoa]).

semrep_semantic_group(livb, [aggp, alga, amph, anim, arch, bact, bird, euka, famg, fish, fngs, grup,
			     humn, invt, mamm, orgm, plnt, podg, popg, prog, rept, rich, virs, vtbt]).

semrep_semantic_group(objc, [enty, food, mnob, phob, sbst]).

semrep_semantic_group(occu, [bmod, ocdi]).

semrep_semantic_group(orga, [hcro, orgt, pros, shro]).

semrep_semantic_group(phen, [biof, eehu, hcpp, lbtr, npop, phpr]).

semrep_semantic_group(phys, [celf, clna, genf, menp, moft, orga, orgf, ortf, phsf]).

semrep_semantic_group(proc, [diap, edac, hlca, lbpr]). % moved topp to tmod
