CC=gcc
LD=gcc
CFLAGS=-O -g -w -fpic
LD_FLAGS=
BERKELEY_DB_LIB=/nfsvol/nls/tools/berkeley_db/db-3.0.55/lib
BERKELEY_DB_INC=/nfsvol/nls/tools/berkeley_db/db-3.0.55/include
OBJ=retrieve_entrezgene_aurelie retrieve_entrezgene_aurelie.o

retrieve_entrezgene_aurelie : retrieve_entrezgene_aurelie.o
	${LD} ${LD_FLAGS} -o retrieve_entrezgene_aurelie retrieve_entrezgene_aurelie.o ${BERKELEY_DB_LIB}/libdb.a -lc

retrieve_entrezgene_aurelie.o : retrieve_entrezgene_aurelie.c
	${CC} ${CFLAGS} -c retrieve_entrezgene_aurelie.c -I. -I${BERKELEY_DB_INC}

