
/****************************************************************************
*
*                          PUBLIC DOMAIN NOTICE                         
*         Lister Hill National Center for Biomedical Communications
*                      National Library of Medicine
*                      National Institues of Health
*           United States Department of Health and Human Services
*                                                                         
*  This software is a United States Government Work under the terms of the
*  United States Copyright Act. It was written as part of the authors'
*  official duties as United States Government employees and contractors
*  and thus cannot be copyrighted. This software is freely available
*  to the public for use. The National Library of Medicine and the
*  United States Government have not placed any restriction on its
*  use or reproduction.
*                                                                        
*  Although all reasonable efforts have been taken to ensure the accuracy 
*  and reliability of the software and data, the National Library of Medicine
*  and the United States Government do not and cannot warrant the performance
*  or results that may be obtained by using this software or data.
*  The National Library of Medicine and the U.S. Government disclaim all
*  warranties, expressed or implied, including warranties of performance,
*  merchantability or fitness for any particular purpose.
*                                                                         
*  For full details, please see the MetaMap Terms & Conditions, available at
*  https://metamap.nlm.nih.gov/MMTnCs.shtml.
*
***************************************************************************/

% File:     sentence_initial_words.pl
% Module:   sentence_initial_words
% Author:   FML
% Purpose:  Define words that are known to begin a sentence
%           immediately after a full stop with no intervening whitespace.

:- module(sentence_initial_words,[
    sentence_initial_word/1
    ]).

% These are all the words in the 2011 Medline Baseline that
% * appear immediately after a "."
% * with no intervening blank space
% * at least 4 times
% * and are no more than 6 characters long.

sentence_initial_word('Abdominal').
sentence_initial_word('Abnormal').
sentence_initial_word('About').
sentence_initial_word('Above').
sentence_initial_word('Absolute').
sentence_initial_word('Absorption').
sentence_initial_word('Abstract').
sentence_initial_word('Abstracts').
sentence_initial_word('Academic').
sentence_initial_word('Acceptance').
sentence_initial_word('Access').
sentence_initial_word('According').
sentence_initial_word('Accounting').
sentence_initial_word('Accuracy').
sentence_initial_word('Accurate').
sentence_initial_word('Acid').
sentence_initial_word('Acquired').
sentence_initial_word('Across').
sentence_initial_word('Acta').
sentence_initial_word('Action').
sentence_initial_word('Activation').
sentence_initial_word('Active').
sentence_initial_word('Activities').
sentence_initial_word('Activity').
sentence_initial_word('Actually').
sentence_initial_word('Actuarial').
sentence_initial_word('Acute').
sentence_initial_word('Adaptation').
sentence_initial_word('Adding').
sentence_initial_word('Addition').
sentence_initial_word('Additional').
sentence_initial_word('Adequate').
sentence_initial_word('Adherence').
sentence_initial_word('Adipose').
sentence_initial_word('Adjusted').
sentence_initial_word('Adjusting').
sentence_initial_word('Adoption').
sentence_initial_word('Adrenal').
sentence_initial_word('Adsorption').
sentence_initial_word('Adult').
sentence_initial_word('Adults').
sentence_initial_word('Advances').
sentence_initial_word('Adverse').
sentence_initial_word('Aerobic').
sentence_initial_word('Aerosol').
sentence_initial_word('African').
sentence_initial_word('After').
sentence_initial_word('Again').
sentence_initial_word('Against').
sentence_initial_word('Agents').
sentence_initial_word('Aging').
sentence_initial_word('Agreement').
sentence_initial_word('Aims').
sentence_initial_word('Alaska').
sentence_initial_word('Alcohol').
sentence_initial_word('Allele').
sentence_initial_word('Almost').
sentence_initial_word('Along').
sentence_initial_word('Alpha').
sentence_initial_word('Also').
sentence_initial_word('Although').
sentence_initial_word('Altogether').
sentence_initial_word('Alzheimer').
sentence_initial_word('Ambient').
sentence_initial_word('American').
sentence_initial_word('Amino').
sentence_initial_word('Ammonium').
sentence_initial_word('Among').
sentence_initial_word('Amongst').
sentence_initial_word('Anaerobic').
sentence_initial_word('Anal').
sentence_initial_word('Analgesia').
sentence_initial_word('Analyses').
sentence_initial_word('Analysis').
sentence_initial_word('Analytical').
sentence_initial_word('Analyzing').
sentence_initial_word('Androgen').
sentence_initial_word('Anemia').
sentence_initial_word('Anesthesia').
sentence_initial_word('Animal').
sentence_initial_word('Animals').
sentence_initial_word('Anion').
sentence_initial_word('Ankle').
sentence_initial_word('Another').
sentence_initial_word('Anterior').
sentence_initial_word('Anti').
sentence_initial_word('Antibiotic').
sentence_initial_word('Antibodies').
sentence_initial_word('Antibody').
sentence_initial_word('Antigenic').
sentence_initial_word('Aortic').
sentence_initial_word('Apart').
sentence_initial_word('Apparent').
sentence_initial_word('Apparently').
sentence_initial_word('Applied').
sentence_initial_word('Apply').
sentence_initial_word('Applying').
sentence_initial_word('Approaches').
sentence_initial_word('April').
sentence_initial_word('Apropos').
sentence_initial_word('Area').
sentence_initial_word('Areas').
sentence_initial_word('Army').
sentence_initial_word('Array').
sentence_initial_word('Arrhenius').
sentence_initial_word('Arterial').
sentence_initial_word('Articles').
sentence_initial_word('Artificial').
sentence_initial_word('Aspects').
sentence_initial_word('Aspirin').
sentence_initial_word('Assessment').
sentence_initial_word('Associated').
sentence_initial_word('Assuming').
sentence_initial_word('Asthma').
sentence_initial_word('Athletes').
sentence_initial_word('Atlantic').
sentence_initial_word('Atlas').
sentence_initial_word('Atrial').
sentence_initial_word('Atropine').
sentence_initial_word('Attached').
sentence_initial_word('Attempts').
sentence_initial_word('Attendees').
sentence_initial_word('Attention').
sentence_initial_word('Atypical').
sentence_initial_word('Australian').
sentence_initial_word('Authors').
sentence_initial_word('Autoimmune').
sentence_initial_word('Auxin').
sentence_initial_word('Available').
sentence_initial_word('Average').
sentence_initial_word('Averaged').
sentence_initial_word('Awareness').
sentence_initial_word('Axial').
sentence_initial_word('Bacillus').
sentence_initial_word('Background').
sentence_initial_word('Bacterial').
sentence_initial_word('Baker').
sentence_initial_word('Balance').
sentence_initial_word('Barr').
sentence_initial_word('Bartlett').
sentence_initial_word('Basal').
sentence_initial_word('Based').
sentence_initial_word('Baseline').
sentence_initial_word('Basic').
sentence_initial_word('Bean').
sentence_initial_word('Because').
sentence_initial_word('Before').
sentence_initial_word('Behavioral').
sentence_initial_word('Beige').
sentence_initial_word('Being').
sentence_initial_word('Benefit').
sentence_initial_word('Benign').
sentence_initial_word('Beside').
sentence_initial_word('Besides').
sentence_initial_word('Best').
sentence_initial_word('Beta').
sentence_initial_word('Better').
sentence_initial_word('Between').
sentence_initial_word('Beyond').
sentence_initial_word('Biceps').
sentence_initial_word('Bilateral').
sentence_initial_word('Bind').
sentence_initial_word('Binding').
sentence_initial_word('Biol').
sentence_initial_word('Biological').
sentence_initial_word('Biomedical').
sentence_initial_word('Biopsy').
sentence_initial_word('Birth').
sentence_initial_word('Bivariate').
sentence_initial_word('Black').
sentence_initial_word('Blake').
sentence_initial_word('Bleeding').
sentence_initial_word('Blinding').
sentence_initial_word('Blood').
sentence_initial_word('Body').
sentence_initial_word('Bone').
sentence_initial_word('Both').
sentence_initial_word('Bovine').
sentence_initial_word('Boys').
sentence_initial_word('Bragg').
sentence_initial_word('Brain').
sentence_initial_word('Braun').
sentence_initial_word('Breast').
sentence_initial_word('Brief').
sentence_initial_word('Briefly').
sentence_initial_word('Bright').
sentence_initial_word('British').
sentence_initial_word('Broadly').
sentence_initial_word('Brown').
sentence_initial_word('Building').
sentence_initial_word('Calcium').
sentence_initial_word('Calculated').
sentence_initial_word('California').
sentence_initial_word('Canada').
sentence_initial_word('Cancer').
sentence_initial_word('Candida').
sentence_initial_word('Carat').
sentence_initial_word('Carbon').
sentence_initial_word('Cardiac').
sentence_initial_word('Care').
sentence_initial_word('Careful').
sentence_initial_word('Carr').
sentence_initial_word('Case').
sentence_initial_word('Cases').
sentence_initial_word('Caution').
sentence_initial_word('Cell').
sentence_initial_word('Cells').
sentence_initial_word('Cellular').
sentence_initial_word('Central').
sentence_initial_word('Cerebral').
sentence_initial_word('Certain').
sentence_initial_word('Certainly').
sentence_initial_word('Cervical').
sentence_initial_word('Challenge').
sentence_initial_word('Change').
sentence_initial_word('Changes').
sentence_initial_word('Changing').
sentence_initial_word('Chem').
sentence_initial_word('Chemical').
sentence_initial_word('Chen').
sentence_initial_word('Chicago').
sentence_initial_word('Child').
sentence_initial_word('Children').
sentence_initial_word('China').
sentence_initial_word('Chiral').
sentence_initial_word('Choice').
sentence_initial_word('Chop').
sentence_initial_word('Chromosome').
sentence_initial_word('Chronic').
sentence_initial_word('Cigarette').
sentence_initial_word('Circular').
sentence_initial_word('Citrate').
sentence_initial_word('Clark').
sentence_initial_word('Clarke').
sentence_initial_word('Class').
sentence_initial_word('Classical').
sentence_initial_word('Clay').
sentence_initial_word('Clear').
sentence_initial_word('Clearly').
sentence_initial_word('Clients').
sentence_initial_word('Clinical').
sentence_initial_word('Clinically').
sentence_initial_word('Clinicians').
sentence_initial_word('Cloning').
sentence_initial_word('Close').
sentence_initial_word('Cluster').
sentence_initial_word('Coaches').
sentence_initial_word('Cocaine').
sentence_initial_word('Code').
sentence_initial_word('Cognitive').
sentence_initial_word('Cold').
sentence_initial_word('Coll').
sentence_initial_word('Collagen').
sentence_initial_word('Collins').
sentence_initial_word('Colloids').
sentence_initial_word('Color').
sentence_initial_word('Combined').
sentence_initial_word('Combining').
sentence_initial_word('Comfort').
sentence_initial_word('Common').
sentence_initial_word('Commonly').
sentence_initial_word('Community').
sentence_initial_word('Compare').
sentence_initial_word('Compared').
sentence_initial_word('Comparing').
sentence_initial_word('Comparison').
sentence_initial_word('Complement').
sentence_initial_word('Complete').
sentence_initial_word('Complex').
sentence_initial_word('Compliance').
sentence_initial_word('Composite').
sentence_initial_word('Compound').
sentence_initial_word('Compounds').
sentence_initial_word('Computed').
sentence_initial_word('Computer').
sentence_initial_word('Concerning').
sentence_initial_word('Concluding').
sentence_initial_word('Conclusion').
sentence_initial_word('Concurrent').
sentence_initial_word('Conditions').
sentence_initial_word('Congenital').
sentence_initial_word('Consistent').
sentence_initial_word('Contact').
sentence_initial_word('Continued').
sentence_initial_word('Continuing').
sentence_initial_word('Continuous').
sentence_initial_word('Contrary').
sentence_initial_word('Contrast').
sentence_initial_word('Control').
sentence_initial_word('Controlled').
sentence_initial_word('Conversely').
sentence_initial_word('Conversion').
sentence_initial_word('Cooling').
sentence_initial_word('Copper').
sentence_initial_word('Cord').
sentence_initial_word('Corn').
sentence_initial_word('Coronary').
sentence_initial_word('Correct').
sentence_initial_word('Corrected').
sentence_initial_word('Cortical').
sentence_initial_word('Cost').
sentence_initial_word('Cotton').
sentence_initial_word('Countries').
sentence_initial_word('Couples').
sentence_initial_word('Coverage').
sentence_initial_word('Creation').
sentence_initial_word('Criteria').
sentence_initial_word('Critical').
sentence_initial_word('Cross').
sentence_initial_word('Crown').
sentence_initial_word('Crude').
sentence_initial_word('Culture').
sentence_initial_word('Cultured').
sentence_initial_word('Cultures').
sentence_initial_word('Cumulative').
sentence_initial_word('Curie').
sentence_initial_word('Current').
sentence_initial_word('Currently').
sentence_initial_word('Curt').
sentence_initial_word('Curves').
sentence_initial_word('Cyanide').
sentence_initial_word('Cyclic').
sentence_initial_word('Cystic').
sentence_initial_word('Cytochrome').
sentence_initial_word('Daily').
sentence_initial_word('Dane').
sentence_initial_word('Dark').
sentence_initial_word('Data').
sentence_initial_word('Date').
sentence_initial_word('David').
sentence_initial_word('Davis').
sentence_initial_word('Deaths').
sentence_initial_word('Decision').
sentence_initial_word('Decrease').
sentence_initial_word('Decreased').
sentence_initial_word('Deep').
sentence_initial_word('Definite').
sentence_initial_word('Definitive').
sentence_initial_word('Delayed').
sentence_initial_word('Delirium').
sentence_initial_word('Delta').
sentence_initial_word('Dens').
sentence_initial_word('Dental').
sentence_initial_word('Depending').
sentence_initial_word('Depression').
sentence_initial_word('Describe').
sentence_initial_word('Design').
sentence_initial_word('Despite').
sentence_initial_word('Detailed').
sentence_initial_word('Detection').
sentence_initial_word('Determine').
sentence_initial_word('Developing').
sentence_initial_word('Diabetes').
sentence_initial_word('Diabetic').
sentence_initial_word('Diagnosis').
sentence_initial_word('Diagnostic').
sentence_initial_word('Diet').
sentence_initial_word('Dietary').
sentence_initial_word('Difference').
sentence_initial_word('Different').
sentence_initial_word('Diffuse').
sentence_initial_word('Digital').
sentence_initial_word('Dimer').
sentence_initial_word('Direct').
sentence_initial_word('Disc').
sentence_initial_word('Discuss').
sentence_initial_word('Discussion').
sentence_initial_word('Disease').
sentence_initial_word('Distal').
sentence_initial_word('Distance').
sentence_initial_word('Doctoring').
sentence_initial_word('Doctors').
sentence_initial_word('Documented').
sentence_initial_word('Does').
sentence_initial_word('Dogs').
sentence_initial_word('Dopamine').
sentence_initial_word('Doppler').
sentence_initial_word('Dosage').
sentence_initial_word('Dose').
sentence_initial_word('Doses').
sentence_initial_word('Double').
sentence_initial_word('Down').
sentence_initial_word('Drinking').
sentence_initial_word('Drug').
sentence_initial_word('Drugs').
sentence_initial_word('Dual').
sentence_initial_word('Duration').
sentence_initial_word('During').
sentence_initial_word('Dynamic').
sentence_initial_word('Each').
sentence_initial_word('Earlier').
sentence_initial_word('Early').
sentence_initial_word('Ecological').
sentence_initial_word('Economic').
sentence_initial_word('Edin').
sentence_initial_word('Editors').
sentence_initial_word('Education').
sentence_initial_word('Effect').
sentence_initial_word('Effective').
sentence_initial_word('Effects').
sentence_initial_word('Efficacy').
sentence_initial_word('Efficiency').
sentence_initial_word('Efflux').
sentence_initial_word('Efforts').
sentence_initial_word('Eight').
sentence_initial_word('Eighteen').
sentence_initial_word('Eighty').
sentence_initial_word('Elderly').
sentence_initial_word('Electron').
sentence_initial_word('Electronic').
sentence_initial_word('Elevated').
sentence_initial_word('Eleven').
sentence_initial_word('Eligible').
sentence_initial_word('Elite').
sentence_initial_word('Embryo').
sentence_initial_word('Emergency').
sentence_initial_word('Emerging').
sentence_initial_word('Emphasis').
sentence_initial_word('Empirical').
sentence_initial_word('Employing').
sentence_initial_word('Empty').
sentence_initial_word('Endemic').
sentence_initial_word('Endoscopic').
sentence_initial_word('Energy').
sentence_initial_word('English').
sentence_initial_word('Enhanced').
sentence_initial_word('Environ').
sentence_initial_word('Enzyme').
sentence_initial_word('Epidural').
sentence_initial_word('Epithelial').
sentence_initial_word('Epsilon').
sentence_initial_word('Equal').
sentence_initial_word('Especially').
sentence_initial_word('Estimated').
sentence_initial_word('Estimates').
sentence_initial_word('Estimation').
sentence_initial_word('Estrogen').
sentence_initial_word('Ethanol').
sentence_initial_word('Ethical').
sentence_initial_word('Ethylene').
sentence_initial_word('European').
sentence_initial_word('Evaluating').
sentence_initial_word('Evaluation').
sentence_initial_word('Evaluator').
sentence_initial_word('Even').
sentence_initial_word('Every').
sentence_initial_word('Evidence').
sentence_initial_word('Examples').
sentence_initial_word('Except').
sentence_initial_word('Excessive').
sentence_initial_word('Exchange').
sentence_initial_word('Exclusion').
sentence_initial_word('Exercise').
sentence_initial_word('Existing').
sentence_initial_word('Exogenous').
sentence_initial_word('Expected').
sentence_initial_word('Experience').
sentence_initial_word('Experiment').
sentence_initial_word('Expert').
sentence_initial_word('Exposed').
sentence_initial_word('Exposure').
sentence_initial_word('Expression').
sentence_initial_word('Extended').
sentence_initial_word('Extensive').
sentence_initial_word('External').
sentence_initial_word('Extra').
sentence_initial_word('Extraction').
sentence_initial_word('Extracts').
sentence_initial_word('Facial').
sentence_initial_word('Factor').
sentence_initial_word('Factors').
sentence_initial_word('Failure').
sentence_initial_word('Family').
sentence_initial_word('Fast').
sentence_initial_word('Fasting').
sentence_initial_word('Fatigue').
sentence_initial_word('Fatty').
sentence_initial_word('Features').
sentence_initial_word('Fecal').
sentence_initial_word('Feeding').
sentence_initial_word('Female').
sentence_initial_word('Females').
sentence_initial_word('Femoral').
sentence_initial_word('Fetal').
sentence_initial_word('Fewer').
sentence_initial_word('Fibrin').
sentence_initial_word('Field').
sentence_initial_word('Fifteen').
sentence_initial_word('Fifty').
sentence_initial_word('Figure').
sentence_initial_word('Filter').
sentence_initial_word('Final').
sentence_initial_word('Finally').
sentence_initial_word('Financial').
sentence_initial_word('Finding').
sentence_initial_word('Findings').
sentence_initial_word('First').
sentence_initial_word('Firstly').
sentence_initial_word('Fischer').
sentence_initial_word('Fish').
sentence_initial_word('Fitness').
sentence_initial_word('Five').
sentence_initial_word('Flow').
sentence_initial_word('Fluid').
sentence_initial_word('Flux').
sentence_initial_word('Focal').
sentence_initial_word('Focus').
sentence_initial_word('Focusing').
sentence_initial_word('Follow').
sentence_initial_word('Following').
sentence_initial_word('Food').
sentence_initial_word('Force').
sentence_initial_word('Forced').
sentence_initial_word('Foreign').
sentence_initial_word('Form').
sentence_initial_word('Forty').
sentence_initial_word('Forward').
sentence_initial_word('Four').
sentence_initial_word('Fourteen').
sentence_initial_word('Fourth').
sentence_initial_word('Fraction').
sentence_initial_word('Fracture').
sentence_initial_word('Fractures').
sentence_initial_word('Frank').
sentence_initial_word('Free').
sentence_initial_word('Freeze').
sentence_initial_word('Frequency').
sentence_initial_word('Frequently').
sentence_initial_word('Fresh').
sentence_initial_word('Freshly').
sentence_initial_word('From').
sentence_initial_word('Frozen').
sentence_initial_word('Full').
sentence_initial_word('Functional').
sentence_initial_word('Further').
sentence_initial_word('Future').
sentence_initial_word('Gait').
sentence_initial_word('Gamma').
sentence_initial_word('Gastric').
sentence_initial_word('Gender').
sentence_initial_word('Gene').
sentence_initial_word('General').
sentence_initial_word('Generally').
sentence_initial_word('Genes').
sentence_initial_word('Genet').
sentence_initial_word('Genetic').
sentence_initial_word('Genetics').
sentence_initial_word('Genome').
sentence_initial_word('Genotype').
sentence_initial_word('Genotypes').
sentence_initial_word('George').
sentence_initial_word('Give').
sentence_initial_word('Given').
sentence_initial_word('Glaucoma').
sentence_initial_word('Global').
sentence_initial_word('Globally').
sentence_initial_word('Glucose').
sentence_initial_word('Glutamate').
sentence_initial_word('Glycerol').
sentence_initial_word('Glycine').
sentence_initial_word('Golden').
sentence_initial_word('Good').
sentence_initial_word('Google').
sentence_initial_word('Grade').
sentence_initial_word('Gradual').
sentence_initial_word('Graft').
sentence_initial_word('Grand').
sentence_initial_word('Granular').
sentence_initial_word('Graphs').
sentence_initial_word('Gray').
sentence_initial_word('Greater').
sentence_initial_word('Greece').
sentence_initial_word('Green').
sentence_initial_word('Gross').
sentence_initial_word('Grossly').
sentence_initial_word('Ground').
sentence_initial_word('Group').
sentence_initial_word('Groups').
sentence_initial_word('Growing').
sentence_initial_word('Growth').
sentence_initial_word('Guidelines').
sentence_initial_word('Guinea').
sentence_initial_word('Hair').
sentence_initial_word('Half').
sentence_initial_word('Harm').
sentence_initial_word('Having').
sentence_initial_word('Head').
sentence_initial_word('Health').
sentence_initial_word('Healthy').
sentence_initial_word('Hearing').
sentence_initial_word('Heart').
sentence_initial_word('Heat').
sentence_initial_word('Heavy').
sentence_initial_word('Height').
sentence_initial_word('Hemoglobin').
sentence_initial_word('Hemorrhage').
sentence_initial_word('Hence').
sentence_initial_word('Heparin').
sentence_initial_word('Hepatic').
sentence_initial_word('Hepatitis').
sentence_initial_word('Here').
sentence_initial_word('Hereditary').
sentence_initial_word('Herein').
sentence_initial_word('High').
sentence_initial_word('Higher').
sentence_initial_word('Highest').
sentence_initial_word('Highly').
sentence_initial_word('Hill').
sentence_initial_word('Hind').
sentence_initial_word('Histology').
sentence_initial_word('Historical').
sentence_initial_word('History').
sentence_initial_word('Home').
sentence_initial_word('Honey').
sentence_initial_word('Hormonal').
sentence_initial_word('Hospital').
sentence_initial_word('Household').
sentence_initial_word('However').
sentence_initial_word('Human').
sentence_initial_word('Hunter').
sentence_initial_word('Hybrid').
sentence_initial_word('Hydrogen').
sentence_initial_word('Hydrolysis').
sentence_initial_word('Hyper').
sentence_initial_word('Ibuprofen').
sentence_initial_word('Ideally').
sentence_initial_word('Identify').
sentence_initial_word('Idiopathic').
sentence_initial_word('Image').
sentence_initial_word('Images').
sentence_initial_word('Imaging').
sentence_initial_word('Immature').
sentence_initial_word('Immediate').
sentence_initial_word('Immune').
sentence_initial_word('Immunity').
sentence_initial_word('Impairment').
sentence_initial_word('Implants').
sentence_initial_word('Important').
sentence_initial_word('Improved').
sentence_initial_word('Improving').
sentence_initial_word('Inasmuch').
sentence_initial_word('Inbred').
sentence_initial_word('Incidence').
sentence_initial_word('Included').
sentence_initial_word('Including').
sentence_initial_word('Inclusion').
sentence_initial_word('Incomplete').
sentence_initial_word('Increased').
sentence_initial_word('Increases').
sentence_initial_word('Increasing').
sentence_initial_word('Incubation').
sentence_initial_word('Indeed').
sentence_initial_word('Indirect').
sentence_initial_word('Individual').
sentence_initial_word('Induction').
sentence_initial_word('Industry').
sentence_initial_word('Infant').
sentence_initial_word('Infants').
sentence_initial_word('Infection').
sentence_initial_word('Infections').
sentence_initial_word('Influenza').
sentence_initial_word('Info').
sentence_initial_word('Infusion').
sentence_initial_word('Inhaled').
sentence_initial_word('Inhibition').
sentence_initial_word('Initial').
sentence_initial_word('Initially').
sentence_initial_word('Injuries').
sentence_initial_word('Instead').
sentence_initial_word('Insulin').
sentence_initial_word('Intact').
sentence_initial_word('Intensive').
sentence_initial_word('Inter').
sentence_initial_word('Interest').
sentence_initial_word('Internal').
sentence_initial_word('Interval').
sentence_initial_word('Interview').
sentence_initial_word('Intestinal').
sentence_initial_word('Intra').
sentence_initial_word('Intrinsic').
sentence_initial_word('Invasive').
sentence_initial_word('Iodine').
sentence_initial_word('Iran').
sentence_initial_word('Iron').
sentence_initial_word('Ironically').
sentence_initial_word('Isolated').
sentence_initial_word('Isolation').
sentence_initial_word('Isotopic').
sentence_initial_word('Italian').
sentence_initial_word('Japanese').
sentence_initial_word('John').
sentence_initial_word('Joint').
sentence_initial_word('Jones').
sentence_initial_word('Joseph').
sentence_initial_word('Journal').
sentence_initial_word('Just').
sentence_initial_word('Kaplan').
sentence_initial_word('Kappa').
sentence_initial_word('Keep').
sentence_initial_word('Keywords').
sentence_initial_word('Khan').
sentence_initial_word('Kidney').
sentence_initial_word('Kinetic').
sentence_initial_word('King').
sentence_initial_word('Knapp').
sentence_initial_word('Knee').
sentence_initial_word('Knowledge').
sentence_initial_word('Koch').
sentence_initial_word('Label').
sentence_initial_word('Labeled').
sentence_initial_word('Labeling').
sentence_initial_word('Laboratory').
sentence_initial_word('Lack').
sentence_initial_word('Lactate').
sentence_initial_word('Lambda').
sentence_initial_word('Large').
sentence_initial_word('Larger').
sentence_initial_word('Larvae').
sentence_initial_word('Laser').
sentence_initial_word('Last').
sentence_initial_word('Lastly').
sentence_initial_word('Late').
sentence_initial_word('Lately').
sentence_initial_word('Later').
sentence_initial_word('Lateral').
sentence_initial_word('Latest').
sentence_initial_word('Lead').
sentence_initial_word('Leaf').
sentence_initial_word('Learning').
sentence_initial_word('Leaves').
sentence_initial_word('Left').
sentence_initial_word('Length').
sentence_initial_word('Lens').
sentence_initial_word('Lesion').
sentence_initial_word('Lesions').
sentence_initial_word('Less').
sentence_initial_word('Level').
sentence_initial_word('Levels').
sentence_initial_word('Lewis').
sentence_initial_word('Life').
sentence_initial_word('Ligand').
sentence_initial_word('Light').
sentence_initial_word('Like').
sentence_initial_word('Likewise').
sentence_initial_word('Limb').
sentence_initial_word('Limitation').
sentence_initial_word('Limited').
sentence_initial_word('Linear').
sentence_initial_word('Linearity').
sentence_initial_word('Ling').
sentence_initial_word('Link').
sentence_initial_word('Lipid').
sentence_initial_word('Lisa').
sentence_initial_word('List').
sentence_initial_word('Literature').
sentence_initial_word('Little').
sentence_initial_word('Live').
sentence_initial_word('Liver').
sentence_initial_word('Local').
sentence_initial_word('Location').
sentence_initial_word('Logistic').
sentence_initial_word('London').
sentence_initial_word('Long').
sentence_initial_word('Longer').
sentence_initial_word('Looking').
sentence_initial_word('Loss').
sentence_initial_word('Losses').
sentence_initial_word('Lower').
sentence_initial_word('Lowering').
sentence_initial_word('Luke').
sentence_initial_word('Lumbar').
sentence_initial_word('Lung').
sentence_initial_word('Lymphocyte').
sentence_initial_word('Lysine').
sentence_initial_word('Magnesium').
sentence_initial_word('Magnetic').
sentence_initial_word('Main').
sentence_initial_word('Major').
sentence_initial_word('Majority').
sentence_initial_word('Malaria').
sentence_initial_word('Male').
sentence_initial_word('Males').
sentence_initial_word('Malignant').
sentence_initial_word('Management').
sentence_initial_word('Mann').
sentence_initial_word('Manual').
sentence_initial_word('Many').
sentence_initial_word('Marc').
sentence_initial_word('Marcus').
sentence_initial_word('Marked').
sentence_initial_word('Market').
sentence_initial_word('Martin').
sentence_initial_word('Mass').
sentence_initial_word('Massage').
sentence_initial_word('Material').
sentence_initial_word('Materials').
sentence_initial_word('Maternal').
sentence_initial_word('Mature').
sentence_initial_word('Maxillary').
sentence_initial_word('Maximal').
sentence_initial_word('Maximum').
sentence_initial_word('Mean').
sentence_initial_word('Meanwhile').
sentence_initial_word('Measured').
sentence_initial_word('Measures').
sentence_initial_word('Measuring').
sentence_initial_word('Mechanical').
sentence_initial_word('Mechanisms').
sentence_initial_word('Median').
sentence_initial_word('Medical').
sentence_initial_word('Medicine').
sentence_initial_word('Medium').
sentence_initial_word('Meeting').
sentence_initial_word('Membrane').
sentence_initial_word('Mental').
sentence_initial_word('Mention').
sentence_initial_word('Mercury').
sentence_initial_word('Meta').
sentence_initial_word('Metabolic').
sentence_initial_word('Metabolism').
sentence_initial_word('Metal').
sentence_initial_word('Metastases').
sentence_initial_word('Method').
sentence_initial_word('Methods').
sentence_initial_word('Meyer').
sentence_initial_word('Mice').
sentence_initial_word('Middle').
sentence_initial_word('Mild').
sentence_initial_word('Milk').
sentence_initial_word('Minimal').
sentence_initial_word('Minimally').
sentence_initial_word('Minimum').
sentence_initial_word('Minor').
sentence_initial_word('Mixed').
sentence_initial_word('Mock').
sentence_initial_word('Mode').
sentence_initial_word('Model').
sentence_initial_word('Moderate').
sentence_initial_word('Modern').
sentence_initial_word('Modified').
sentence_initial_word('Molecular').
sentence_initial_word('Moles').
sentence_initial_word('Monitoring').
sentence_initial_word('Mono').
sentence_initial_word('Mood').
sentence_initial_word('More').
sentence_initial_word('Moreover').
sentence_initial_word('Morphine').
sentence_initial_word('Mortality').
sentence_initial_word('Most').
sentence_initial_word('Mothers').
sentence_initial_word('Motor').
sentence_initial_word('Mouse').
sentence_initial_word('Much').
sentence_initial_word('Mull').
sentence_initial_word('Muller').
sentence_initial_word('Multi').
sentence_initial_word('Multilevel').
sentence_initial_word('Multiple').
sentence_initial_word('Muscle').
sentence_initial_word('Music').
sentence_initial_word('Mutations').
sentence_initial_word('Myocardial').
sentence_initial_word('Nasal').
sentence_initial_word('National').
sentence_initial_word('Native').
sentence_initial_word('Natl').
sentence_initial_word('Natural').
sentence_initial_word('Naturally').
sentence_initial_word('Nausea').
sentence_initial_word('Near').
sentence_initial_word('Nearly').
sentence_initial_word('Necropsy').
sentence_initial_word('Need').
sentence_initial_word('Needs').
sentence_initial_word('Negative').
sentence_initial_word('Neither').
sentence_initial_word('Neonatal').
sentence_initial_word('Neonates').
sentence_initial_word('Neural').
sentence_initial_word('Never').
sentence_initial_word('Newer').
sentence_initial_word('Newly').
sentence_initial_word('Next').
sentence_initial_word('Nine').
sentence_initial_word('Nineteen').
sentence_initial_word('Ninety').
sentence_initial_word('Nitrate').
sentence_initial_word('Nitrite').
sentence_initial_word('Nitrogen').
sentence_initial_word('Nodules').
sentence_initial_word('Noise').
sentence_initial_word('None').
sentence_initial_word('Nordic').
sentence_initial_word('Normal').
sentence_initial_word('Norplant').
sentence_initial_word('Northern').
sentence_initial_word('Notably').
sentence_initial_word('Note').
sentence_initial_word('Novel').
sentence_initial_word('Nowadays').
sentence_initial_word('Nuclear').
sentence_initial_word('Null').
sentence_initial_word('Numb').
sentence_initial_word('Number').
sentence_initial_word('Numbers').
sentence_initial_word('Numerical').
sentence_initial_word('Numerous').
sentence_initial_word('Nurse').
sentence_initial_word('Nurses').
sentence_initial_word('Nursing').
sentence_initial_word('Nutrition').
sentence_initial_word('Obese').
sentence_initial_word('Obesity').
sentence_initial_word('Objective').
sentence_initial_word('Objectives').
sentence_initial_word('Observed').
sentence_initial_word('Obviously').
sentence_initial_word('Occurrence').
sentence_initial_word('Ocular').
sentence_initial_word('Odds').
sentence_initial_word('Older').
sentence_initial_word('Omega').
sentence_initial_word('Once').
sentence_initial_word('Only').
sentence_initial_word('Open').
sentence_initial_word('Opening').
sentence_initial_word('Operative').
sentence_initial_word('Opiate').
sentence_initial_word('Optical').
sentence_initial_word('Optimal').
sentence_initial_word('Oral').
sentence_initial_word('Orbital').
sentence_initial_word('Orsola').
sentence_initial_word('Orthopedic').
sentence_initial_word('Osmotic').
sentence_initial_word('Other').
sentence_initial_word('Outcome').
sentence_initial_word('Outcomes').
sentence_initial_word('Ovarian').
sentence_initial_word('Over').
sentence_initial_word('Overall').
sentence_initial_word('Overweight').
sentence_initial_word('Owing').
sentence_initial_word('Oxidative').
sentence_initial_word('Oxygen').
sentence_initial_word('Ozone').
sentence_initial_word('Pacific').
sentence_initial_word('Pact').
sentence_initial_word('Pain').
sentence_initial_word('Paired').
sentence_initial_word('Pancreatic').
sentence_initial_word('Paper').
sentence_initial_word('Paraffin').
sentence_initial_word('Parallel').
sentence_initial_word('Paralytic').
sentence_initial_word('Parent').
sentence_initial_word('Parental').
sentence_initial_word('Parents').
sentence_initial_word('Paris').
sentence_initial_word('Part').
sentence_initial_word('Partial').
sentence_initial_word('Partially').
sentence_initial_word('Particular').
sentence_initial_word('Passive').
sentence_initial_word('Path').
sentence_initial_word('Pathologic').
sentence_initial_word('Patient').
sentence_initial_word('Patients').
sentence_initial_word('Patterns').
sentence_initial_word('Paul').
sentence_initial_word('Paulo').
sentence_initial_word('Peak').
sentence_initial_word('Pediatric').
sentence_initial_word('Peer').
sentence_initial_word('People').
sentence_initial_word('Peptide').
sentence_initial_word('Performing').
sentence_initial_word('Perhaps').
sentence_initial_word('Perinatal').
sentence_initial_word('Periodic').
sentence_initial_word('Peripheral').
sentence_initial_word('Peritoneal').
sentence_initial_word('Persistent').
sentence_initial_word('Persons').
sentence_initial_word('Peter').
sentence_initial_word('Petersburg').
sentence_initial_word('Pharyngeal').
sentence_initial_word('Phase').
sentence_initial_word('Phil').
sentence_initial_word('Phys').
sentence_initial_word('Physical').
sentence_initial_word('Physician').
sentence_initial_word('Physicians').
sentence_initial_word('Physiology').
sentence_initial_word('Pilot').
sentence_initial_word('Pituitary').
sentence_initial_word('Placebo').
sentence_initial_word('Plain').
sentence_initial_word('Plant').
sentence_initial_word('Plants').
sentence_initial_word('Plasma').
sentence_initial_word('Plastic').
sentence_initial_word('Platelet').
sentence_initial_word('Players').
sentence_initial_word('Please').
sentence_initial_word('Policy').
sentence_initial_word('Pooled').
sentence_initial_word('Poor').
sentence_initial_word('Population').
sentence_initial_word('Port').
sentence_initial_word('Position').
sentence_initial_word('Positive').
sentence_initial_word('Possible').
sentence_initial_word('Possibly').
sentence_initial_word('Post').
sentence_initial_word('Posterior').
sentence_initial_word('Postnatal').
sentence_initial_word('Potassium').
sentence_initial_word('Potential').
sentence_initial_word('Power').
sentence_initial_word('Practical').
sentence_initial_word('Practice').
sentence_initial_word('Precise').
sentence_initial_word('Precision').
sentence_initial_word('Predictors').
sentence_initial_word('Preface').
sentence_initial_word('Pregnancy').
sentence_initial_word('Pregnant').
sentence_initial_word('Premature').
sentence_initial_word('Presence').
sentence_initial_word('Present').
sentence_initial_word('Presented').
sentence_initial_word('Presently').
sentence_initial_word('Pressure').
sentence_initial_word('Prevalence').
sentence_initial_word('Prevention').
sentence_initial_word('Previous').
sentence_initial_word('Previously').
sentence_initial_word('Primarily').
sentence_initial_word('Primary').
sentence_initial_word('Principal').
sentence_initial_word('Prior').
sentence_initial_word('Problems').
sentence_initial_word('Procedural').
sentence_initial_word('Production').
sentence_initial_word('Professor').
sentence_initial_word('Profiles').
sentence_initial_word('Prognosis').
sentence_initial_word('Program').
sentence_initial_word('Progress').
sentence_initial_word('Project').
sentence_initial_word('Prolonged').
sentence_initial_word('Promising').
sentence_initial_word('Proper').
sentence_initial_word('Prosthetic').
sentence_initial_word('Protection').
sentence_initial_word('Protein').
sentence_initial_word('Proteins').
sentence_initial_word('Proton').
sentence_initial_word('Provide').
sentence_initial_word('Provision').
sentence_initial_word('Proximal').
sentence_initial_word('Public').
sentence_initial_word('Published').
sentence_initial_word('Pulmonary').
sentence_initial_word('Pulse').
sentence_initial_word('Pure').
sentence_initial_word('Purified').
sentence_initial_word('Purpose').
sentence_initial_word('Pushkin').
sentence_initial_word('Pylori').
sentence_initial_word('Quality').
sentence_initial_word('Questions').
sentence_initial_word('Radiation').
sentence_initial_word('Radical').
sentence_initial_word('Random').
sentence_initial_word('Randomized').
sentence_initial_word('Rank').
sentence_initial_word('Ransom').
sentence_initial_word('Rapid').
sentence_initial_word('Rapidly').
sentence_initial_word('Rate').
sentence_initial_word('Rates').
sentence_initial_word('Rather').
sentence_initial_word('Ratio').
sentence_initial_word('Rats').
sentence_initial_word('Reaction').
sentence_initial_word('Reactions').
sentence_initial_word('Reactive').
sentence_initial_word('Readers').
sentence_initial_word('Real').
sentence_initial_word('Reasons').
sentence_initial_word('Receiver').
sentence_initial_word('Recent').
sentence_initial_word('Recently').
sentence_initial_word('Recognize').
sentence_initial_word('Records').
sentence_initial_word('Recovery').
sentence_initial_word('Rectal').
sentence_initial_word('Recurrence').
sentence_initial_word('Recurrent').
sentence_initial_word('Reduced').
sentence_initial_word('Reducing').
sentence_initial_word('Reduction').
sentence_initial_word('Reference').
sentence_initial_word('Refractive').
sentence_initial_word('Regarding').
sentence_initial_word('Regardless').
sentence_initial_word('Regional').
sentence_initial_word('Regression').
sentence_initial_word('Regular').
sentence_initial_word('Relative').
sentence_initial_word('Relatively').
sentence_initial_word('Relevant').
sentence_initial_word('Relief').
sentence_initial_word('Remarkably').
sentence_initial_word('Removal').
sentence_initial_word('Renal').
sentence_initial_word('Repair').
sentence_initial_word('Repeat').
sentence_initial_word('Repeated').
sentence_initial_word('Report').
sentence_initial_word('Reported').
sentence_initial_word('Reporting').
sentence_initial_word('Reports').
sentence_initial_word('Research').
sentence_initial_word('Residual').
sentence_initial_word('Resistance').
sentence_initial_word('Responding').
sentence_initial_word('Response').
sentence_initial_word('Responses').
sentence_initial_word('Resting').
sentence_initial_word('Result').
sentence_initial_word('Results').
sentence_initial_word('Retinal').
sentence_initial_word('Reversal').
sentence_initial_word('Reverse').
sentence_initial_word('Review').
sentence_initial_word('Revision').
sentence_initial_word('Rhenium').
sentence_initial_word('Rheumatoid').
sentence_initial_word('Rich').
sentence_initial_word('Richter').
sentence_initial_word('Right').
sentence_initial_word('Risk').
sentence_initial_word('Risks').
sentence_initial_word('Road').
sentence_initial_word('Robert').
sentence_initial_word('Robinson').
sentence_initial_word('Robotic').
sentence_initial_word('Room').
sentence_initial_word('Root').
sentence_initial_word('Roots').
sentence_initial_word('Rosa').
sentence_initial_word('Routine').
sentence_initial_word('Ruptured').
sentence_initial_word('Rural').
sentence_initial_word('Russet').
sentence_initial_word('Rutgers').
sentence_initial_word('Ruth').
sentence_initial_word('Safety').
sentence_initial_word('Salinity').
sentence_initial_word('Salivary').
sentence_initial_word('Salmonella').
sentence_initial_word('Salt').
sentence_initial_word('Sample').
sentence_initial_word('Samples').
sentence_initial_word('Sampling').
sentence_initial_word('Scan').
sentence_initial_word('Scanning').
sentence_initial_word('Schneider').
sentence_initial_word('Scoping').
sentence_initial_word('Scores').
sentence_initial_word('Scout').
sentence_initial_word('Screening').
sentence_initial_word('Seal').
sentence_initial_word('Search').
sentence_initial_word('Searches').
sentence_initial_word('Season').
sentence_initial_word('Seasonal').
sentence_initial_word('Second').
sentence_initial_word('Secondary').
sentence_initial_word('Secondly').
sentence_initial_word('Section').
sentence_initial_word('Sedentary').
sentence_initial_word('Seed').
sentence_initial_word('Seedlings').
sentence_initial_word('Segments').
sentence_initial_word('Selected').
sentence_initial_word('Selection').
sentence_initial_word('Selective').
sentence_initial_word('Selenium').
sentence_initial_word('Self').
sentence_initial_word('Semi').
sentence_initial_word('Senior').
sentence_initial_word('Sensory').
sentence_initial_word('Separate').
sentence_initial_word('Separation').
sentence_initial_word('Sequence').
sentence_initial_word('Sequences').
sentence_initial_word('Sequencing').
sentence_initial_word('Sequential').
sentence_initial_word('Serial').
sentence_initial_word('Serious').
sentence_initial_word('Serous').
sentence_initial_word('Serum').
sentence_initial_word('Setting').
sentence_initial_word('Settings').
sentence_initial_word('Seven').
sentence_initial_word('Seventeen').
sentence_initial_word('Seventy').
sentence_initial_word('Several').
sentence_initial_word('Severe').
sentence_initial_word('Severity').
sentence_initial_word('Sexual').
sentence_initial_word('Shock').
sentence_initial_word('Shoots').
sentence_initial_word('Short').
sentence_initial_word('Shoulder').
sentence_initial_word('Side').
sentence_initial_word('Sight').
sentence_initial_word('Sigma').
sentence_initial_word('Sign').
sentence_initial_word('Silver').
sentence_initial_word('Similar').
sentence_initial_word('Similarly').
sentence_initial_word('Simon').
sentence_initial_word('Simple').
sentence_initial_word('Simulation').
sentence_initial_word('Since').
sentence_initial_word('Single').
sentence_initial_word('Site').
sentence_initial_word('Sixteen').
sentence_initial_word('Sixty').
sentence_initial_word('Skeletal').
sentence_initial_word('Skin').
sentence_initial_word('Slabs').
sentence_initial_word('Sleep').
sentence_initial_word('Slight').
sentence_initial_word('Slow').
sentence_initial_word('Small').
sentence_initial_word('Smart').
sentence_initial_word('Smith').
sentence_initial_word('Smoking').
sentence_initial_word('Snow').
sentence_initial_word('Soccer').
sentence_initial_word('Social').
sentence_initial_word('Sodium').
sentence_initial_word('Software').
sentence_initial_word('Soil').
sentence_initial_word('Soluble').
sentence_initial_word('Solutions').
sentence_initial_word('Solvent').
sentence_initial_word('Some').
sentence_initial_word('Sometimes').
sentence_initial_word('Source').
sentence_initial_word('Southern').
sentence_initial_word('Sparkle').
sentence_initial_word('Spec').
sentence_initial_word('Special').
sentence_initial_word('Species').
sentence_initial_word('Specific').
sentence_initial_word('Specimens').
sentence_initial_word('Speech').
sentence_initial_word('Speed').
sentence_initial_word('Spinal').
sentence_initial_word('Spleen').
sentence_initial_word('Sports').
sentence_initial_word('Spot').
sentence_initial_word('Stage').
sentence_initial_word('Stages').
sentence_initial_word('Standard').
sentence_initial_word('Starch').
sentence_initial_word('Starting').
sentence_initial_word('State').
sentence_initial_word('Statistics').
sentence_initial_word('Stats').
sentence_initial_word('Steady').
sentence_initial_word('Steering').
sentence_initial_word('Stem').
sentence_initial_word('Step').
sentence_initial_word('Stepwise').
sentence_initial_word('Stern').
sentence_initial_word('Sterne').
sentence_initial_word('Steroid').
sentence_initial_word('Steroids').
sentence_initial_word('Still').
sentence_initial_word('Stomach').
sentence_initial_word('Stone').
sentence_initial_word('Stop').
sentence_initial_word('Storage').
sentence_initial_word('Strains').
sentence_initial_word('Strategies').
sentence_initial_word('Strength').
sentence_initial_word('Stress').
sentence_initial_word('Strict').
sentence_initial_word('Stroke').
sentence_initial_word('Strong').
sentence_initial_word('Strontium').
sentence_initial_word('Structural').
sentence_initial_word('Student').
sentence_initial_word('Students').
sentence_initial_word('Studies').
sentence_initial_word('Study').
sentence_initial_word('Subgroup').
sentence_initial_word('Subjective').
sentence_initial_word('Subjects').
sentence_initial_word('Subsequent').
sentence_initial_word('Success').
sentence_initial_word('Successful').
sentence_initial_word('Such').
sentence_initial_word('Sucrose').
sentence_initial_word('Sudden').
sentence_initial_word('Sugar').
sentence_initial_word('Sulfate').
sentence_initial_word('Sulfur').
sentence_initial_word('Summary').
sentence_initial_word('Sunday').
sentence_initial_word('Supp').
sentence_initial_word('Support').
sentence_initial_word('Supporting').
sentence_initial_word('Surf').
sentence_initial_word('Surface').
sentence_initial_word('Surgeons').
sentence_initial_word('Surgery').
sentence_initial_word('Surgical').
sentence_initial_word('Survey').
sentence_initial_word('Surveys').
sentence_initial_word('Survival').
sentence_initial_word('Suspension').
sentence_initial_word('Swiss').
sentence_initial_word('Symptoms').
sentence_initial_word('Synthesis').
sentence_initial_word('Synthetic').
sentence_initial_word('System').
sentence_initial_word('Systematic').
sentence_initial_word('Systemic').
sentence_initial_word('Systolic').
sentence_initial_word('Table').
sentence_initial_word('Tables').
sentence_initial_word('Tailored').
sentence_initial_word('Taken').
sentence_initial_word('Taking').
sentence_initial_word('Tandem').
sentence_initial_word('Target').
sentence_initial_word('Targeting').
sentence_initial_word('Task').
sentence_initial_word('Teachers').
sentence_initial_word('Team').
sentence_initial_word('Tech').
sentence_initial_word('Technical').
sentence_initial_word('Technique').
sentence_initial_word('Techniques').
sentence_initial_word('Tell').
sentence_initial_word('Temporal').
sentence_initial_word('Tension').
sentence_initial_word('Test').
sentence_initial_word('Tested').
sentence_initial_word('Testicular').
sentence_initial_word('Testing').
sentence_initial_word('Tests').
sentence_initial_word('Tetanus').
sentence_initial_word('Text').
sentence_initial_word('That').
sentence_initial_word('Their').
sentence_initial_word('Then').
sentence_initial_word('Theories').
sentence_initial_word('Therapy').
sentence_initial_word('There').
sentence_initial_word('Thereafter').
sentence_initial_word('Thereby').
sentence_initial_word('Therefore').
sentence_initial_word('These').
sentence_initial_word('They').
sentence_initial_word('Thin').
sentence_initial_word('Third').
sentence_initial_word('Thirdly').
sentence_initial_word('Thirteen').
sentence_initial_word('Thirty').
sentence_initial_word('This').
sentence_initial_word('Thomas').
sentence_initial_word('Those').
sentence_initial_word('Though').
sentence_initial_word('Three').
sentence_initial_word('Through').
sentence_initial_word('Throughout').
sentence_initial_word('Thus').
sentence_initial_word('Thyroid').
sentence_initial_word('Time').
sentence_initial_word('Timing').
sentence_initial_word('Tinnitus').
sentence_initial_word('Tissue').
sentence_initial_word('Tobacco').
sentence_initial_word('Today').
sentence_initial_word('Together').
sentence_initial_word('Tolerance').
sentence_initial_word('Tonic').
sentence_initial_word('Topical').
sentence_initial_word('Torque').
sentence_initial_word('Torr').
sentence_initial_word('Total').
sentence_initial_word('Totally').
sentence_initial_word('Towards').
sentence_initial_word('Toxic').
sentence_initial_word('Toxicity').
sentence_initial_word('Train').
sentence_initial_word('Training').
sentence_initial_word('Trans').
sentence_initial_word('Transfer').
sentence_initial_word('Transient').
sentence_initial_word('Transplant').
sentence_initial_word('Transport').
sentence_initial_word('Transverse').
sentence_initial_word('Trauma').
sentence_initial_word('Treating').
sentence_initial_word('Treatment').
sentence_initial_word('Treatments').
sentence_initial_word('Trellis').
sentence_initial_word('Trends').
sentence_initial_word('Trial').
sentence_initial_word('Trials').
sentence_initial_word('Triple').
sentence_initial_word('True').
sentence_initial_word('Trunk').
sentence_initial_word('Trypsin').
sentence_initial_word('Tubes').
sentence_initial_word('Tumor').
sentence_initial_word('Tumors').
sentence_initial_word('Twelve').
sentence_initial_word('Twenty').
sentence_initial_word('Twin').
sentence_initial_word('Type').
sentence_initial_word('Types').
sentence_initial_word('Typical').
sentence_initial_word('Typically').
sentence_initial_word('Tyrosine').
sentence_initial_word('Ultimately').
sentence_initial_word('Ultra').
sentence_initial_word('Ultrasound').
sentence_initial_word('Under').
sentence_initial_word('Understand').
sentence_initial_word('Univariate').
sentence_initial_word('Universal').
sentence_initial_word('University').
sentence_initial_word('Unlike').
sentence_initial_word('Unloading').
sentence_initial_word('Until').
sentence_initial_word('Untreated').
sentence_initial_word('Upon').
sentence_initial_word('Upper').
sentence_initial_word('Uptake').
sentence_initial_word('Urban').
sentence_initial_word('Urea').
sentence_initial_word('Urinary').
sentence_initial_word('Urine').
sentence_initial_word('Used').
sentence_initial_word('Using').
sentence_initial_word('Usually').
sentence_initial_word('Uterine').
sentence_initial_word('Utilizing').
sentence_initial_word('Vaccine').
sentence_initial_word('Vaccines').
sentence_initial_word('Vacuoles').
sentence_initial_word('Vaginal').
sentence_initial_word('Valencia').
sentence_initial_word('Validation').
sentence_initial_word('Value').
sentence_initial_word('Values').
sentence_initial_word('Variable').
sentence_initial_word('Variables').
sentence_initial_word('Variants').
sentence_initial_word('Variation').
sentence_initial_word('Variations').
sentence_initial_word('Various').
sentence_initial_word('Vascular').
sentence_initial_word('Velocity').
sentence_initial_word('Venous').
sentence_initial_word('Venus').
sentence_initial_word('Vertical').
sentence_initial_word('Very').
sentence_initial_word('Vibrio').
sentence_initial_word('Video').
sentence_initial_word('Vincent').
sentence_initial_word('Vinyl').
sentence_initial_word('Viral').
sentence_initial_word('Virtual').
sentence_initial_word('Virus').
sentence_initial_word('Viruses').
sentence_initial_word('Visceral').
sentence_initial_word('Visual').
sentence_initial_word('Vitamin').
sentence_initial_word('Viva').
sentence_initial_word('Volume').
sentence_initial_word('Walking').
sentence_initial_word('Walter').
sentence_initial_word('Washing').
sentence_initial_word('Water').
sentence_initial_word('Webb').
sentence_initial_word('Weight').
sentence_initial_word('Weighted').
sentence_initial_word('Well').
sentence_initial_word('Wells').
sentence_initial_word('Western').
sentence_initial_word('What').
sentence_initial_word('Whatever').
sentence_initial_word('When').
sentence_initial_word('Whenever').
sentence_initial_word('Where').
sentence_initial_word('Whereas').
sentence_initial_word('Whether').
sentence_initial_word('Which').
sentence_initial_word('While').
sentence_initial_word('Whilst').
sentence_initial_word('White').
sentence_initial_word('Whole').
sentence_initial_word('Wide').
sentence_initial_word('Wild').
sentence_initial_word('Will').
sentence_initial_word('Williams').
sentence_initial_word('Wilting').
sentence_initial_word('With').
sentence_initial_word('Withdrawal').
sentence_initial_word('Within').
sentence_initial_word('Without').
sentence_initial_word('Women').
sentence_initial_word('Work').
sentence_initial_word('Working').
sentence_initial_word('Workplace').
sentence_initial_word('Worldwide').
sentence_initial_word('Wound').
sentence_initial_word('Wright').
sentence_initial_word('Xhosa').
sentence_initial_word('Young').
sentence_initial_word('Younger').
sentence_initial_word('Youth').
sentence_initial_word('Zinc').
