


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                                    %%%
%%%           IMPORTANT:               %%%
%%%    DO NOT MODIFY THIS FILE:        %%%
%%%    IT IS MACHINE-GENERATED         %%%
%%%  from the semantic_groups file     %%%
%%% in $SAW/src/Usemrep/usemrep_domain %%%
%%%                                    %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

:- module(semgroup_member, [semrep_semgroup_member/2, semgen_semgroup_member/2]).

semgen_semgroup_member(anst,anat).
semgen_semgroup_member(blor,anat).
semgen_semgroup_member(bpoc,anat).
semgen_semgroup_member(bsoj,anat).
semgen_semgroup_member(bdsu,anat).
semgen_semgroup_member(cell,anat).
semgen_semgroup_member(celc,anat).
semgen_semgroup_member(emst,anat).
semgen_semgroup_member(ffas,anat).
semgen_semgroup_member(tisu,anat).
semgen_semgroup_member(acab,diso).
semgen_semgroup_member(anab,diso).
semgen_semgroup_member(cgab,diso).
semgen_semgroup_member(dsyn,diso).
semgen_semgroup_member(inpo,diso).
semgen_semgroup_member(mobd,diso).
semgen_semgroup_member(neop,diso).
semgen_semgroup_member(patf,diso).
semgen_semgroup_member(aapp,gene).
semgen_semgroup_member(gngm,gene).
semgen_semgroup_member(nnon,gene).
semgen_semgroup_member(nusq,gene).
semgen_semgroup_member(antb,chem).
semgen_semgroup_member(bacs,chem).
semgen_semgroup_member(bodm,chem).
semgen_semgroup_member(carb,chem).
semgen_semgroup_member(chem,chem).
semgen_semgroup_member(chvf,chem).
semgen_semgroup_member(chvs,chem).
semgen_semgroup_member(clnd,chem).
semgen_semgroup_member(eico,chem).
semgen_semgroup_member(elii,chem).
semgen_semgroup_member(enzy,chem).
semgen_semgroup_member(hops,chem).
semgen_semgroup_member(horm,chem).
semgen_semgroup_member(imft,chem).
semgen_semgroup_member(irda,chem).
semgen_semgroup_member(inch,chem).
semgen_semgroup_member(lipd,chem).
semgen_semgroup_member(nsba,chem).
semgen_semgroup_member(orch,chem).
semgen_semgroup_member(opco,chem).
semgen_semgroup_member(phsu,chem).
semgen_semgroup_member(rcpt,chem).
semgen_semgroup_member(strd,chem).
semgen_semgroup_member(vita,chem).
semrep_semgroup_member(aapp,tmod).
semrep_semgroup_member(antb,tmod).
semrep_semgroup_member(bacs,tmod).
semrep_semgroup_member(carb,tmod).
semrep_semgroup_member(chem,tmod).
semrep_semgroup_member(chvf,tmod).
semrep_semgroup_member(chvs,tmod).
semrep_semgroup_member(clnd,tmod).
semrep_semgroup_member(eico,tmod).
semrep_semgroup_member(elii,tmod).
semrep_semgroup_member(enzy,tmod).
semrep_semgroup_member(hops,tmod).
semrep_semgroup_member(horm,tmod).
semrep_semgroup_member(imft,tmod).
semrep_semgroup_member(inch,tmod).
semrep_semgroup_member(lipd,tmod).
semrep_semgroup_member(nnon,tmod).
semrep_semgroup_member(nsba,tmod).
semrep_semgroup_member(opco,tmod).
semrep_semgroup_member(orch,tmod).
semrep_semgroup_member(phsu,tmod).
semrep_semgroup_member(rcpt,tmod).
semrep_semgroup_member(strd,tmod).
semrep_semgroup_member(vita,tmod).
semrep_semgroup_member(medd,tmod).
semrep_semgroup_member(topp,tmod).
semrep_semgroup_member(acty,acti).
semrep_semgroup_member(bhvr,acti).
semrep_semgroup_member(dora,acti).
semrep_semgroup_member(evnt,acti).
semrep_semgroup_member(gora,acti).
semrep_semgroup_member(inbe,acti).
semrep_semgroup_member(mcha,acti).
semrep_semgroup_member(ocac,acti).
semrep_semgroup_member(socb,acti).
semrep_semgroup_member(anst,anat).
semrep_semgroup_member(bdsu,anat).
semrep_semgroup_member(bdsy,anat).
semrep_semgroup_member(blor,anat).
semrep_semgroup_member(bpoc,anat).
semrep_semgroup_member(bsoj,anat).
semrep_semgroup_member(celc,anat).
semrep_semgroup_member(cell,anat).
semrep_semgroup_member(emst,anat).
semrep_semgroup_member(ffas,anat).
semrep_semgroup_member(tisu,anat).
semrep_semgroup_member(clas,conc).
semrep_semgroup_member(cnce,conc).
semrep_semgroup_member(ftcn,conc).
semrep_semgroup_member(grpa,conc).
semrep_semgroup_member(idcn,conc).
semrep_semgroup_member(inpr,conc).
semrep_semgroup_member(lang,conc).
semrep_semgroup_member(qlco,conc).
semrep_semgroup_member(qnco,conc).
semrep_semgroup_member(rnlw,conc).
semrep_semgroup_member(spco,conc).
semrep_semgroup_member(tmco,conc).
semrep_semgroup_member(drdd,devi).
semrep_semgroup_member(resd,devi).
semrep_semgroup_member(acab,diso).
semrep_semgroup_member(anab,diso).
semrep_semgroup_member(cgab,diso).
semrep_semgroup_member(comd,diso).
semrep_semgroup_member(dsyn,diso).
semrep_semgroup_member(fndg,diso).
semrep_semgroup_member(inpo,diso).
semrep_semgroup_member(mobd,diso).
semrep_semgroup_member(neop,diso).
semrep_semgroup_member(patf,diso).
semrep_semgroup_member(sosy,diso).
semrep_semgroup_member(aapp,gene).
semrep_semgroup_member(amas,gene).
semrep_semgroup_member(crbs,gene).
semrep_semgroup_member(gngm,gene).
semrep_semgroup_member(mosq,gene).
semrep_semgroup_member(nusq,gene).
semrep_semgroup_member(geoa,geog).
semrep_semgroup_member(aggp,livb).
semrep_semgroup_member(alga,livb).
semrep_semgroup_member(amph,livb).
semrep_semgroup_member(anim,livb).
semrep_semgroup_member(arch,livb).
semrep_semgroup_member(bact,livb).
semrep_semgroup_member(bird,livb).
semrep_semgroup_member(euka,livb).
semrep_semgroup_member(famg,livb).
semrep_semgroup_member(fish,livb).
semrep_semgroup_member(fngs,livb).
semrep_semgroup_member(grup,livb).
semrep_semgroup_member(humn,livb).
semrep_semgroup_member(invt,livb).
semrep_semgroup_member(mamm,livb).
semrep_semgroup_member(orgm,livb).
semrep_semgroup_member(plnt,livb).
semrep_semgroup_member(podg,livb).
semrep_semgroup_member(popg,livb).
semrep_semgroup_member(prog,livb).
semrep_semgroup_member(rept,livb).
semrep_semgroup_member(rich,livb).
semrep_semgroup_member(virs,livb).
semrep_semgroup_member(vtbt,livb).
semrep_semgroup_member(enty,objc).
semrep_semgroup_member(food,objc).
semrep_semgroup_member(mnob,objc).
semrep_semgroup_member(phob,objc).
semrep_semgroup_member(sbst,objc).
semrep_semgroup_member(bmod,occu).
semrep_semgroup_member(ocdi,occu).
semrep_semgroup_member(hcro,orga).
semrep_semgroup_member(orgt,orga).
semrep_semgroup_member(pros,orga).
semrep_semgroup_member(shro,orga).
semrep_semgroup_member(biof,phen).
semrep_semgroup_member(eehu,phen).
semrep_semgroup_member(hcpp,phen).
semrep_semgroup_member(lbtr,phen).
semrep_semgroup_member(npop,phen).
semrep_semgroup_member(phpr,phen).
semrep_semgroup_member(celf,phys).
semrep_semgroup_member(clna,phys).
semrep_semgroup_member(genf,phys).
semrep_semgroup_member(menp,phys).
semrep_semgroup_member(moft,phys).
semrep_semgroup_member(orga,phys).
semrep_semgroup_member(orgf,phys).
semrep_semgroup_member(ortf,phys).
semrep_semgroup_member(phsf,phys).
semrep_semgroup_member(diap,proc).
semrep_semgroup_member(edac,proc).
semrep_semgroup_member(hlca,proc).
semrep_semgroup_member(lbpr,proc).
